# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

# Make sure that branch and PR triggers are enabled in Travis CI settings on the web UI, and then
# it will run whenever a PR is opened and whenever a new commit is merged into one of these branches
branches:
  only:
    - master

git:
  depth: 2

# Node version
node_js: "17.4.0"

before_install:
  # Dynamically create an `.npmrc` file
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > "$HOME/.npmrc"
  # Ensure that npm version is 8.4.0
  - if [[ `npm -v` != 8.4.0 ]]; then npm i -g npm@8.4.0; fi
  - npm install -g yarn@1.22.5
  # Install pre-commit
  - curl https://pre-commit.com/install-local.py | python -
  # To ensure the aws command can be found
  - export PATH=$PATH:$HOME/.local/bin

# Install top level dependencies
install:
  - yarn && cd example && yarn && cd ..

# the following line is needed to enable the TravisCI build conditions
conditions: v1

# Run these commands
jobs:
  include:
    # ##### #
    # Tests #
    # ##### #

    # Run pre-commit hooks on all files
    - stage: test
      name: Pre-Commits
      script:
        - pre-commit run --all-files

    # Run tests on multiple browsers and publish code coverage
    - stage: test
      name: Cross-Browser Tests
      script:
        - yarn test:browserstack
        - yarn report-coverage

    # ###### #
    # Deploy #
    # ###### #

    # Deploy to npm
    - stage: deploy
      script: skip
      edge: true
      deploy:
        - provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          on:
            branch: master

cache:
  directories:
    # Cache pre-commit repos so that the pre-commit setup is faster
    - $HOME/.cache/pre-commit
    # Cache npm as specified by https://docs.npmjs.com/cli/ci#example
    # - This will wipe node_modules (to ensure a valid build), so caching can't
    #   be used to speed the install up
    - $HOME/.npm
before_cache:
  - rm -f $HOME/.cache/pre-commit/pre-commit.log
  - rm -f $HOME/.npm/anonymous-cli-metrics.json
